In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('C:/Users/Isyrak/Desktop/FYP PROJECT/Dataset/hepatitisData.csv')
print(len(dataset))
print(dataset.head())

589
   CATEGORY  AGE  SEX   ALB   ALP   ALT   AST   BIL    CHE  CHOL   CREA   GGT  \
0         0   32    0  38.5  52.5   7.7  22.1   7.5   6.93  3.23  106.0  12.1   
1         0   32    0  38.5  70.3  18.0  24.7   3.9  11.17  4.80   74.0  15.6   
2         0   32    0  46.9  74.7  36.2  52.6   6.1   8.84  5.20   86.0  33.2   
3         0   32    0  43.2  52.0  30.6  22.6  18.9   7.33  4.74   80.0  33.8   
4         0   32    0  39.2  74.1  32.6  24.8   9.6   9.15  4.32   76.0  29.9   

   PROT  
0  69.0  
1  76.5  
2  79.3  
3  75.7  
4  68.7  


In [3]:
zero_not_accepted = ['AGE','ALB','ALP','AST','BIL','CHE','CHOL','CREA','GGT','PROT']

for column in zero_not_accepted:
    dataset[column] = dataset[column].replace(0,np.NaN)
    mean = int(dataset[column].mean(skipna=True))
    dataset[column] = dataset[column].replace(np.NaN, mean)

In [4]:
X = dataset.iloc[:,1:13]
y = dataset.iloc[:,0]
X


AGE  SEX   ALB    ALP   ALT    AST   BIL    CHE  CHOL   CREA    GGT  PROT
0     32    0  38.5   52.5   7.7   22.1   7.5   6.93  3.23  106.0   12.1  69.0
1     32    0  38.5   70.3  18.0   24.7   3.9  11.17  4.80   74.0   15.6  76.5
2     32    0  46.9   74.7  36.2   52.6   6.1   8.84  5.20   86.0   33.2  79.3
3     32    0  43.2   52.0  30.6   22.6  18.9   7.33  4.74   80.0   33.8  75.7
4     32    0  39.2   74.1  32.6   24.8   9.6   9.15  4.32   76.0   29.9  68.7
..   ...  ...   ...    ...   ...    ...   ...    ...   ...    ...    ...   ...
584   58    1  34.0   46.4  15.0  150.0   8.0   6.26  3.98   56.0   49.7  80.6
585   59    1  39.0   51.3  19.6  285.8  40.0   5.77  4.51  136.1  101.1  70.5
586   62    1  32.0  416.6   5.9  110.3  50.0   5.57  6.30   55.7  650.9  68.5
587   64    1  24.0  102.8   2.9   44.4  20.0   1.54  3.02   63.0   35.9  71.3
588   64    1  29.0   87.3   3.5   99.0  48.0   1.66  3.63   66.7   64.2  82.0

[589 rows x 12 columns]

In [5]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)


In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [7]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=150,random_state=0)
model.fit(X_train,y_train)
score = model.score(X_test,y_test)
print(score)

0.9491525423728814


In [8]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 4, 0, 2, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[106   0   0   0   0]
 [  1   0   0   0   0]
 [  1   0   1   1   0]
 [  0   0   2   1   0]
 [  1   0   0   0   4]]


In [10]:
import pickle
pickle.dump(model,open('rfmodel','wb'))